### ISSUE TITLE
table-rename-isHoverable: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Andrei-Stepanov** [patternfly/pf-codemods#541]
Hello,

Could you please help me?
I am following: https://www.patternfly.org/get-started/upgrade/release-notes/
I get an error:

```
➜  osci npx @patternfly/pf-codemods@latest ciboard
Need to install the following packages:
  @patternfly/pf-codemods@1.82.1
Ok to proceed? (y) 
/home/astepano/.npm/_npx/d72ba669e7bba25a/node_modules/@patternfly/eslint-plugin-pf-codemods/lib/rules/v5/table-rename-isHoverable.js:10
    ).imports.filter((specifier) => ["Table", "Tr"].includes(specifier.imported.name));
                                                                                ^

TypeError: Error while loading rule '@patternfly/pf-codemods/table-rename-isHoverable': Cannot read properties of undefined (reading 'name')
Occurred while linting /home/astepano/osci/ciboard/src/components/SSTResultsTable.tsx
    at /home/astepano/.npm/_npx/d72ba669e7bba25a/node_modules/@patternfly/eslint-plugin-pf-codemods/lib/rules/v5/table-rename-isHoverable.js:10:81
    at Array.filter (<anonymous>)
    at Object.create (/home/astepano/.npm/_npx/d72ba669e7bba25a/node_modules/@patternfly/eslint-plugin-pf-codemods/lib/rules/v5/table-rename-isHoverable.js:10:15)
    at createRuleListeners (/home/astepano/.npm/_npx/d72ba669e7bba25a/node_modules/eslint/lib/linter/linter.js:910:21)
    at /home/astepano/.npm/_npx/d72ba669e7bba25a/node_modules/eslint/lib/linter/linter.js:1081:110
    at Array.forEach (<anonymous>)
    at runRules (/home/astepano/.npm/_npx/d72ba669e7bba25a/node_modules/eslint/lib/linter/linter.js:1018:34)
    at Linter._verifyWithoutProcessors (/home/astepano/.npm/_npx/d72ba669e7bba25a/node_modules/eslint/lib/linter/linter.js:1370:31)
    at Linter._verifyWithConfigArray (/home/astepano/.npm/_npx/d72ba669e7bba25a/node_modules/eslint/lib/linter/linter.js:1822:21)
    at Linter.verify (/home/astepano/.npm/_npx/d72ba669e7bba25a/node_modules/eslint/lib/linter/linter.js:1452:65)
```

```
node --version
v16.19.1


grep patter package.json 
    "@patternfly/react-charts": "^6.67.1",
    "@patternfly/react-core": "^4.276.6",
    "@patternfly/react-icons": "^4.65.1",
    "@patternfly/react-table": "^4.113.0",
```

**Comment by Andrei-Stepanov** [comment]
Hi,
Update from a discussion on Slack with Dallas Nicol, it turned out that the place of error was: 

```
import ReactTable from '@patternfly/react-table';

This commit fixed it:

https://github.com/fedora-ci/ciboard/commit/7c869d249eee4ff1147200b52fe3d8099c55c1dc

**Comment by gitdallas** [comment]
As this is pretty uncommon and not a super trivial fix, I wonder if it would be good enough to ignore specifiers without import names (these default imports) by using the `specifier.imported?.name` (will have to check for all such instances in codemods) and then adding another codemod that just checks for such import specifiers and gives a warning like:

> /src/path/file.tsx
>  10:1 warning This import specifier does not have an import name. The codemods will be unable to check against it.

**Comment by fantonangeli** [comment]
We had the same error with this import:
```typescript
import * as Patternfly from "@patternfly/react-core";
```
https://github.com/apache/incubator-kie-tools/blob/013678c0b3128d6682cc332f1e016df47cf8983d/packages/runtime-tools-shared-enveloped-components/src/formDisplayer/envelope/components/ReactFormRenderer/ReactFormRenderer.tsx#L24

Using `specifier.imported?.name` in the rule fixes it.

The error:
```
TypeError: Error while loading rule '@patternfly/pf-codemods/aboutModalBoxHero-remove-subcomponent': Cannot read properties of undefined (reading 'name')
```
